# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/io.ipynb.

# %% auto 0
__all__ = ['load_json', 'save_json']

# %% ../notebooks/io.ipynb 2
import json

# %% ../notebooks/io.ipynb 3
def load_json(f):
    with open(f) as f:
        return json.load(f)


def save_json(obj, f):
    with open(f, "w") as f:
        json.dump(obj, f)
