# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/io.ipynb.

# %% auto 0
__all__ = ['load_json', 'save_json', 'load_pickle', 'save_pickle']

# %% ../notebooks/io.ipynb 2
import json
import pickle

# %% ../notebooks/io.ipynb 3
def load_json(f):
    with open(f) as f:
        return json.load(f)


def save_json(obj, f):
    with open(f, "w") as f:
        json.dump(obj, f)

# %% ../notebooks/io.ipynb 4
def load_pickle(f):
    with open(f, "rb") as f:
        return pickle.load(f)


def save_pickle(obj, f):
    with open(f, "wb") as f:
        pickle.dump(obj, f)
